Info spot implementation
HSLdevcom/jore4-tiamat pull request #41
Opened 2024-08-28 16:20 UTC by culka

Info spot implementation
Info spot poster implementation
Database migration
GraphQL API to read and write values
GraphQL tests for info spots

2024-08-29 11:22 UTC, Huulivoide requested changes
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41)* status: all files reviewed, 17 unresolved discussions (waiting on @culka)

___
*[`src/main/java/org/rutebanken/tiamat/model/DisplayTypeEnumeration.java` line 29 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5S_ZHO7x9kq46Byk8x:-O5S_ZHO7x9kq46Byk8y:bpwn4ty) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/model/DisplayTypeEnumeration.java#L29)):*
> ```Java
>         }
> 
>         throw new IllegalArgumentException(v);
> ```

Tähän ois voinut laittaa vielä jonkun tarkemman virheviestin: `"(${v}) Is not a value included in DisplayTypeEnumeration"`
___
*[`src/main/java/org/rutebanken/tiamat/model/InfoSpot.java` line 16 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5SaHVI8UfRgdouzIIT:-O5SaHVJ7___wzwH7u8f:b-sfwvsb) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/model/InfoSpot.java#L16)):*
> ```Java
>                 @UniqueConstraint(name = "info_spot_netex_id_version_constraint", columnNames = {"netexId", "version"})}
> )
> public class InfoSpot extends InfoSpot_VersionStructure implements Serializable {
> ```

Serialisoitavissa luokissa pitäis aina olla käsin määriteltynä `static final long serialVersionUID`, sanoo koodityökaluty ja java dokkarit.
___
*[`src/main/java/org/rutebanken/tiamat/model/InfoSpot_VersionStructure.java` line 13 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5Sd_4NBURVTCalQI2a:-O5Sd_4NBURVTCalQI2b:bjfi2kq) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/model/InfoSpot_VersionStructure.java#L13)):*
> ```Java
> import java.util.HashSet;
> import java.util.Set;
> import java.util.stream.Collectors;
> ```

Onkohan täällä Tiamatin puolella, mitään koodi formatteria olemassa.
Tää nimittäin taitaa olla, en ainakaan nää koodeissa käyttöä, tarpeeton importti.
___
*[`src/main/java/org/rutebanken/tiamat/model/InfoSpot_VersionStructure.java` line 18 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5ScLrHAF0k_87NeLzL:-O5ScLrHAF0k_87NeLzM:b8lzb7g) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/model/InfoSpot_VersionStructure.java#L18)):*
> ```Java
> public class InfoSpot_VersionStructure extends DataManagedObjectStructure {
> 
>     protected InfoSpotTypeEnumeration infoSpotType;
> ```

Onks nää tarkotuksella protected eikä private? Jos tätä joku luokka extendaa, niin voisko se mennä getter-settereillä?
___
*[`src/main/java/org/rutebanken/tiamat/model/InfoSpot_VersionStructure.java` line 147 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5SbjPy0mW1GSrInokY:-O5SbjPy0mW1GSrInokZ:bd558l1) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/model/InfoSpot_VersionStructure.java#L147)):*
> ```Java
> 
>     public void setInfoSpotLocations(Collection<String> infoSpotLocation) {
>         this.infoSpotLocations = new HashSet<>(infoSpotLocation);
> ```

Ellei tarkotuksellisesti tarvita mutablea settiä niin `Set.copyOf(x)` ois parempi, niin lentää sitten virheitä, jos joku yrittää tota arvoa ulkopuolelta alkaan mutatoimaan, sen sijaan että vetää `get, modify, set-new` linjalla.
___
*[`src/main/java/org/rutebanken/tiamat/model/InfoSpotPoster.java` line 11 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5Sc2WL1Te0YOjIZVmi:-O5Sc2WL1Te0YOjIZVmj:b-24j9c0) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/model/InfoSpotPoster.java#L11)):*
> ```Java
> @Entity
> public class InfoSpotPoster extends InfoSpotPoster_VersionStructure implements Serializable {
> ```

Tääl kanssa serialVersionUID
___
*[`src/main/java/org/rutebanken/tiamat/model/InfoSpotTypeEnumeration.java` line 25 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5Sd5s9DPSU1I2ZjhUW:-O5Sd5s9DPSU1I2ZjhUX:bh5y0gv) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/model/InfoSpotTypeEnumeration.java#L25)):*
> ```Java
>         }
> 
>         throw new IllegalArgumentException(value);
> ```

Taitaa olla jo olemass aoleva patterni, että heitetään vaan annettu stringi virheviestinä', eikä kerrota oikeeta syytä.
___
*[`src/main/java/org/rutebanken/tiamat/model/PosterSizeEnumeration.java` line 26 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5SdDadCcZUhr95xvvP:-O5SdDadCcZUhr95xvvQ:bz53iew) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/model/PosterSizeEnumeration.java#L26)):*
> ```Java
>         }
> 
>         throw new IllegalArgumentException(v);
> ```

Tääl kanssa sama 🤷🏻‍♂️
___
*[`src/main/java/org/rutebanken/tiamat/repository/InfoSpotPosterRepositoryImpl.java` line 40 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5SdrAQC_uEnBVOV5oR:-O5SdrAQC_uEnBVOV5oS:b9s3eti) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/repository/InfoSpotPosterRepositoryImpl.java#L40)):*
> ```Java
>             if (results.isEmpty()) {
>                 return null;
>             } else {
> ```

Else wräppäyksen voi poistaa.
___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotPosterFetcher.java` line 13 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5SexZN1UZtynSxkVso:-O5SexZN1UZtynSxkVsp:bqyysf7) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotPosterFetcher.java#L13)):*
> ```Java
> import org.springframework.stereotype.Component;
> 
> @Component
> ```

Tää on vaan `@Component` mutta `InfoSpotsFetcher` on `@Service("joll on nimi")`. Onko tälle joku syy? 
___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotPosterFetcher.java` line 30 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5SegTa40VlqJ_6E4u2:-O5SegTa40VlqJ_6E4u3:boalwot) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotPosterFetcher.java#L30)):*
> ```Java
>                     .toList();
>         }
>         return new ArrayList<>();
> ```

Varmaan jo olemassaoleva käytäntö, mutta mukavampi olis pelailla immutable datan kaa, eli `Collections.emptyList()`
___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsFetcher.java` line 14 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5Sg0nyAXjAsWMhDTIQ:-O5Sg0nz9HQziKN9bO7L:bus1ngu) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsFetcher.java#L14)):*
> ```Java
> 
> @Service("infoSpotsFetcher")
> @Transactional
> ```

Mää pistäsin tän transaktion tonne metodiin, joka sitä vaatii. Ei tähän varmana koskaan mitään lisää metodeja tule, et sen puoleen varmana ihan yks ja sama, mutta ellei tää oo joki codebasen käytäntö, niin selkeempihän se olis että se on siellä missä sitä tarvitaan.
___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsUpdater.java` line 85 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5ShrxH4bRfl2vwcsQk:-O5ShrxH4bRfl2vwcsQl:b-rcc4xz) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/re [...]

2024-08-29 14:49 UTC, culka reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41)* status: all files reviewed, 17 unresolved discussions (waiting on @Huulivoide)

___
*[`src/main/java/org/rutebanken/tiamat/model/DisplayTypeEnumeration.java` line 29 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5S_ZHO7x9kq46Byk8x:-O5TGY7J0hCI8cVG3hni:brj4yoj) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/model/DisplayTypeEnumeration.java#L29)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tähän ois voinut laittaa vielä jonkun tarkemman virheviestin: `"(${v}) Is not a value included in DisplayTypeEnumeration"`
</blockquote></details>

Käytössä kaikissa muissa enumeraatioissa.
___
*[`src/main/java/org/rutebanken/tiamat/model/InfoSpot.java` line 16 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5SaHVI8UfRgdouzIIT:-O5TaQgP1lNVwWHbWMwT:b-nelqbz) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/model/InfoSpot.java#L16)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Serialisoitavissa luokissa pitäis aina olla käsin määriteltynä `static final long serialVersionUID`, sanoo koodityökaluty ja java dokkarit.
</blockquote></details>

Minkähän vuoksi Tiamatissa ei ole muualla näitä käytössä ollenkaan... Ja kyllä IDEA on itse asiassa aiemmin valittanut tästä ja tarjonnut automaattigeneroitua ID:tä.

Oli disabloituna asetuksista.
___
*[`src/main/java/org/rutebanken/tiamat/model/InfoSpot_VersionStructure.java` line 13 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5Sd_4NBURVTCalQI2a:-O5TA1oD78-i8N288fsC:b-43yf22) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/model/InfoSpot_VersionStructure.java#L13)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Onkohan täällä Tiamatin puolella, mitään koodi formatteria olemassa.
Tää nimittäin taitaa olla, en ainakaan nää koodeissa käyttöä, tarpeeton importti.
</blockquote></details>

Ei ole käytössä mitään, olemassaolevasta koodista lentäisi niin paljon ilmoituksia.
___
*[`src/main/java/org/rutebanken/tiamat/model/InfoSpot_VersionStructure.java` line 18 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5ScLrHAF0k_87NeLzL:-O5TAWVE55ne5wdq4kBS:booti2h) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/model/InfoSpot_VersionStructure.java#L18)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Onks nää tarkotuksella protected eikä private? Jos tätä joku luokka extendaa, niin voisko se mennä getter-settereillä?
</blockquote></details>

Olemassaolevissa `_VersionStructure`eissa oli kaikki protected, ja tehty samalla mallilla.
___
*[`src/main/java/org/rutebanken/tiamat/model/InfoSpot_VersionStructure.java` line 147 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5SbjPy0mW1GSrInokY:-O5TGg2KAOzSrZrzUmqx:b-bc12ge) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/model/InfoSpot_VersionStructure.java#L147)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Ellei tarkotuksellisesti tarvita mutablea settiä niin `Set.copyOf(x)` ois parempi, niin lentää sitten virheitä, jos joku yrittää tota arvoa ulkopuolelta alkaan mutatoimaan, sen sijaan että vetää `get, modify, set-new` linjalla.
</blockquote></details>

Muutettu.
___
*[`src/main/java/org/rutebanken/tiamat/model/InfoSpotPoster.java` line 11 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5Sc2WL1Te0YOjIZVmi:-O5Tb0DP9JRMB2WG0ZCK:b-v9609z) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/model/InfoSpotPoster.java#L11)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tääl kanssa serialVersionUID
</blockquote></details>

Korjattu.
___
*[`src/main/java/org/rutebanken/tiamat/model/InfoSpotTypeEnumeration.java` line 25 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5Sd5s9DPSU1I2ZjhUW:-O5TBgWBAsGzWKiEkYhZ:btgql1k) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/model/InfoSpotTypeEnumeration.java#L25)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Taitaa olla jo olemass aoleva patterni, että heitetään vaan annettu stringi virheviestinä', eikä kerrota oikeeta syytä.
</blockquote></details>

Jep, sama kaikissa olemassaolevissa enumeraatioissa, mutta eipä se ole syy olla tekemättä paremmin :slightly_smiling_face: 
___
*[`src/main/java/org/rutebanken/tiamat/model/PosterSizeEnumeration.java` line 26 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5SdDadCcZUhr95xvvP:-O5TGissCl9z4ecvLZu3:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/model/PosterSizeEnumeration.java#L26)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tääl kanssa sama 🤷🏻‍♂️
</blockquote></details>

:+1: 
___
*[`src/main/java/org/rutebanken/tiamat/repository/InfoSpotPosterRepositoryImpl.java` line 40 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5SdrAQC_uEnBVOV5oR:-O5TZDN90zOo7h_2ygs7:bb6vst0) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/repository/InfoSpotPosterRepositoryImpl.java#L40)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Else wräppäyksen voi poistaa.
</blockquote></details>

Fixd
___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotPosterFetcher.java` line 13 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5SexZN1UZtynSxkVso:-O5TC4Dy9v2AXb55FB-8:b-cz3m3q) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotPosterFetcher.java#L13)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tää on vaan `@Component` mutta `InfoSpotsFetcher` on `@Service("joll on nimi")`. Onko tälle joku syy?
</blockquote></details>

`InfoSpotPosterFetcher`ia ei käytetä suoraan entityjen hakemiseen, vaan `InfoSpot`iin liittyvät posterit haetaan sillä. En nyt näe syytä miksi se on komponentti, mutta näin oli tehty kaikissa jo olemassaolevissa samanlaisissa fetchereissä.
___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotPosterFetcher.java` line 30 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5SegTa40VlqJ_6E4u2:-O5TFfTC0EyPNQqeyC9a:b8jawti) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotPosterFetcher.java#L30)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Varmaan jo olemassaoleva käytäntö, mutta mukavampi olis pelailla immutable datan kaa, eli `Collections.emptyList()`
</blockquote></details>

Muutettu kivemmin funktionaaliseksi.
___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsFetcher.java` line 14 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5Sg0nyAXjAsWMhDTIQ:-O5TZfQsCCLjpwwnWq74:bu9r43j) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/098dca7879b86208f460fee31a47297c3883dc14/ [...]

2024-08-30 07:52 UTC, Huulivoide approved these changes
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @culka)



<!-- Sent from Reviewable.io -->

2024-09-04 13:18 UTC, culka reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41)* status: 17 of 26 files reviewed, 19 unresolved discussions (waiting on @Huulivoide and @Leitsi)

___
*[`src/main/java/org/rutebanken/tiamat/repository/InfoSpotPosterRepositoryImpl.java` line 30 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5m_VKO8wnI4ipn1KLS:-O5sCTMK2UCEGZXH6Jx6:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/c4423c28bead18afbac5bf28875d00d87215e619/src/main/java/org/rutebanken/tiamat/repository/InfoSpotPosterRepositoryImpl.java#L30)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

parking?

If we don't use this method, could just `throw new NotImplementedException("findFirstByKeyValues not implemented for " \+ this.getClass().getSimpleName());` like in many other places. Otherwise, should be tested.
</blockquote></details>

Done.
___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/GraphQLNames.java` line 550 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5m_p9O5u1aJU3asLEQ:-O5sCUBSCfc1u0WOp_Lu:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/c4423c28bead18afbac5bf28875d00d87215e619/src/main/java/org/rutebanken/tiamat/rest/graphql/GraphQLNames.java#L550)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Here the output type is with capital letter, but `OUTPUT_TYPE_POSTER` is not. Which one goes against common conventions?
</blockquote></details>

Done.
___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/StopPlaceRegisterGraphQLSchema.java` line 734 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5maBfO3wIPwalPZ_wF:-O5sD9Hm5KfogcNh79ID:bgsm6ib) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/c4423c28bead18afbac5bf28875d00d87215e619/src/main/java/org/rutebanken/tiamat/rest/graphql/StopPlaceRegisterGraphQLSchema.java#L734)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Should this be closer to info spot data ferfet registers?
</blockquote></details>

Moved all the info spot registrations next to each other.
___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsUpdater.java` line 59 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5ml5Ol0nJxYPeEQM4I:-O5sDPXLD6t2-_zfBcTu:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/c4423c28bead18afbac5bf28875d00d87215e619/src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsUpdater.java#L59)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Not used.
</blockquote></details>

Done.
___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsUpdater.java` line 74 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5ml6FbBaPJUtgKufl5:-O5sDj22CFsIyNDAn-4V:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/c4423c28bead18afbac5bf28875d00d87215e619/src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsUpdater.java#L74)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Not used.
</blockquote></details>

Done.
___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsUpdater.java` line 95 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5mlDM85PbZ2Dy1o5Qq:-O5sDosfEH44MWt59Jyl:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/c4423c28bead18afbac5bf28875d00d87215e619/src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsUpdater.java#L95)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

`target` variable not used.
</blockquote></details>

Done.
___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsUpdater.java` line 203 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5mmLr1EKrgMdGd9dYy:-O5sDzHjE7DEamk6ovbR:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/c4423c28bead18afbac5bf28875d00d87215e619/src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsUpdater.java#L203)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Could reformat these long lines a bit for better readability.
</blockquote></details>

Done.
___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsUpdater.java` line 213 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5mlw3F3TZtFiYTWEih:-O5sE0LU-PKE__ycqLJI:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/c4423c28bead18afbac5bf28875d00d87215e619/src/main/java/org/rutebanken/tiamat/rest/graphql/fetchers/InfoSpotsUpdater.java#L213)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

logger forgotten here.
</blockquote></details>

Done.
___
*[`src/main/java/org/rutebanken/tiamat/rest/graphql/types/InfoSpotObjectTypeCreator.java` line 88 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5mmp_kA-CzIswUQxc1:-O5sE1fvAYNZpqYN8pOk:b-cxa7al) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/c4423c28bead18afbac5bf28875d00d87215e619/src/main/java/org/rutebanken/tiamat/rest/graphql/types/InfoSpotObjectTypeCreator.java#L88)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I don't think I saw this in tests :thinking:
</blockquote></details>

Geometry has been added.
___
*[`src/main/java/org/rutebanken/tiamat/versioning/VersionIncrementor.java` line 156 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5mn2o5AlqJq2R3zhX0:-O5sEG7233oDuwx-ZORk:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/c4423c28bead18afbac5bf28875d00d87215e619/src/main/java/org/rutebanken/tiamat/versioning/VersionIncrementor.java#L156)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Trailing spaces.
</blockquote></details>

Done.
___
*[`src/main/java/org/rutebanken/tiamat/versioning/save/InfoSpotPosterVersionedSaverService.java` line 19 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5mnBP6-0EZozXTlwU9:-O5x-Uuy9DdiL4fRy2es:bqk3o3h) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/c4423c28bead18afbac5bf28875d00d87215e619/src/main/java/org/rutebanken/tiamat/versioning/save/InfoSpotPosterVersionedSaverService.java#L19)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

`seve`

This doesn't seem to be used. So, is something broken, possibly not tested then?
</blockquote></details>

This was not used when saving new posters even though it was meant to. In use now.
___
*[`src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceInfoSpotIntegrationTest.java` line 57 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5m9M03DtbatGPfT1sk:-O5x-T9v0kJMwguXJ_M5:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/c4423c28bead18afbac5bf28875d00d87215e619/src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceInfoSpotIntegrationTest.java#L57)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Could check size here as well, `.body("data.infoSpots", hasSize(2))` I think.
</blockquote></details>

Done.
___
*[`src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceInfoSpotIntegrationTest.java` line 125 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5m9_Mh08gVgSz01RpG:-O5x-Ol0Dt6V6OiK2NpB:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/c4423c28bead18afbac5bf28875d00d87215e619/src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceInfoSpotIntegrationTest.java#L125)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Should check size here, nothing ensures now that this doesn't eg just return all versions. `.body("data.infoSpots", hasS [...]

2024-09-05 07:19 UTC, Leitsi requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41)* status: 17 of 26 files reviewed, 2 unresolved discussions (waiting on @culka and @Huulivoide)

___
*[`src/main/java/org/rutebanken/tiamat/versioning/save/InfoSpotPosterVersionedSaverService.java` line 19 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5mnBP6-0EZozXTlwU9:-O601gVv7SUxRZnI9WSv:b-qlv8ey) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/c4423c28bead18afbac5bf28875d00d87215e619/src/main/java/org/rutebanken/tiamat/versioning/save/InfoSpotPosterVersionedSaverService.java#L19)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

This was not used when saving new posters even though it was meant to. In use now.
</blockquote></details>

`seve` typo still here.
___
*[`src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceInfoSpotIntegrationTest.java` line 216 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-O5mByc9ABjv5of0dE3w:-O601zc4DR8bPTsEhxl8:b-siuqb1) ([raw file](https://github.com/HSLdevcom/jore4-tiamat/blob/c4423c28bead18afbac5bf28875d00d87215e619/src/test/java/org/rutebanken/tiamat/rest/graphql/GraphQLResourceInfoSpotIntegrationTest.java#L216)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

One `.toLowerCase()` still remains here. I don't think it's needed?


<!-- Sent from Reviewable.io -->

2024-09-05 10:59 UTC, Leitsi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-tiamat/41#-:-O60pltE0mZq8K_g06NN:bnfp4nl)* status: 16 of 26 files reviewed, all discussions resolved (waiting on @Huulivoide)



<!-- Sent from Reviewable.io -->

2024-09-05 11:47 UTC, merged