Dockerized working build
HSLdevcom/jore4-tiamat pull request #8
Opened 2023-12-05 05:44 UTC by culka

Create a dockerized working build which works together with Jore4 development environment. Does not yet work with the cloud since that requires flux config changes, which require a working build first.

2023-12-14 14:24 UTC, jarkkoka requested changes
> Reviewed 5 of 8 files at r1, 16 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 21 of 23 files reviewed, 16 unresolved discussions (waiting on @culka)

___
*[`.gitignore` line 47 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nlcd8Wl6bq5D2jPh23D:-Nlcd8Wl6bq5D2jPh23E:b-17ampd) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/.gitignore#L47)):*
> ```ignore
> node_modules
> 
> !src/main/resources/helper-jars/*.jar
> ```

Hmmm....helper jars in `src/main/resources` folder. Looks very weird. What is really going on here?
___
*[`Dockerfile` line 31 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlcdVTt6yFxqbrxeHL3:-NlcdVTt6yFxqbrxeHL4:b5l1npc) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/Dockerfile#L31)):*
> ```Dockerfile
> 
> RUN mvn install:install-file \
> -Dfile=src/main/resources/helper-jars/hazelcast4-helper-1.89-SNAPSHOT.jar \
> ```

This `1.89-SNAPSHOT` version is repeated multiple times. IMO you should introduce an environment variable for it.
___
*[`Dockerfile` line 40 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nlcdk1XCsL7u-fiLMjH:-Nlcdk1XCsL7u-fiLMjI:b-rgk49g) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/Dockerfile#L40)):*
> ```Dockerfile
> RUN mvn clean package spring-boot:repackage -DskipTests
> 
> FROM amazoncorretto:11-al2-full
> ```

I think we should not use Amazon Corretto. Look what we use in other JVM project repositories.
___
*[`development.sh` line 56 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nlce9CD7yPwhE9NSpMM:-Nlce9CD7yPwhE9NSpMN:b34onku) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/development.sh#L56)):*
> ```Shell
>     Start hastus service in Docker container
> 
>   start-dependencies
> ```

`start:deps` is used in our other repositories. IMO the cognitive load would be reduced if we stick to common naming.
___
*[`development.sh` line 81 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nlce4J775oX1AlWg0Eu:-Nlce4J775oX1AlWg0Ev:b34onku) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/development.sh#L81)):*
> ```Shell
>     ;;
> 
>   start-dependencies)
> ```

`start:deps` is used in our other repositories. IMO the cognitive load would be reduced if we stick to common naming.
___
*[`.github/workflows/docker-build.yml` line 17 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nlcecfj77ZzTlip2W02:-Nlcecfj77ZzTlip2W03:b-z9cw9y) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/.github/workflows/docker-build.yml#L17)):*
> ```YAML
>     steps:
>       - name: Checkout code
>         uses: actions/checkout@v3
> ```

`@v4` is the latest. Let's change to it.
___
*[`.github/workflows/run-cypress-tests.yml` line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlcfBrcEqCE9Y97EjG5:-NlcfBrcEqCE9Y97EjG6:b2nhaqh) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/.github/workflows/run-cypress-tests.yml#L15)):*
> ```YAML
>     steps:
>       - name: Checkout code
>         uses: actions/checkout@v3
> ```

@v4
___
*[`src/main/java/org/rutebanken/tiamat/auth/TiamatSecurityConfig.java` line 61 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nlcfags5JHFMGS0bfmC:-Nlcfags5JHFMGS0bfmD:b-m5aa14) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/java/org/rutebanken/tiamat/auth/TiamatSecurityConfig.java#L61)):*
> ```Java
> 
> 		logger.info("Configuring HttpSecurity");
> 		http.cors(withDefaults())
> ```

Replace tabs with spaces.
___
*[`src/main/java/org/rutebanken/tiamat/changelog/EntityChangedEventDummyPublisher.java` line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlcfgxbDlK8WHdl3RuK:-NlcfgxbDlK8WHdl3RuL:b9affk4) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/java/org/rutebanken/tiamat/changelog/EntityChangedEventDummyPublisher.java#L15)):*
> ```Java
> public class EntityChangedEventDummyPublisher extends EntityChangedEventPublisher implements EntityChangedListener {
> 
>     private static final Logger log = LoggerFactory.getLogger(EntityChangedEventDummyPublisher.class);
> ```

Uppercase: `log` -> `LOG`
___
*[`src/main/java/org/rutebanken/tiamat/changelog/EntityChangedEventPubSubPublisher.java` line 31 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlcghtG3N2ahekFPowc:-NlcghtG3N2ahekFPowd:bxwi4fq) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/java/org/rutebanken/tiamat/changelog/EntityChangedEventPubSubPublisher.java#L31)):*
> ```Java
> public class EntityChangedEventPubSubPublisher extends EntityChangedEventPublisher implements EntityChangedListener {
> 
> // TODO: Remove? Google pubsub is not used
> ```

Maybe this whole class could be removed.
___
*[`src/main/java/org/rutebanken/tiamat/config/GooglePubSubConfig.java` line 12 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlcgqAc2Woe0h9nH0Td:-NlcgqAc2Woe0h9nH0Te:be3bzn1) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/java/org/rutebanken/tiamat/config/GooglePubSubConfig.java#L12)):*
> ```Java
> import org.springframework.messaging.MessageHandler;
> 
> // TODO: Remove properly. Google pubsub is not used
> ```

Couldn't you delete the whole class
___
*[`src/main/java/org/rutebanken/tiamat/config/OAuth2Config.java` line 61 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nlch5dc11SZPsnt9OHG:-Nlch5dc11SZPsnt9OHH:bzbe37d) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/java/org/rutebanken/tiamat/config/OAuth2Config.java#L61)):*
> ```Java
>         //String rorAuth0Issuer = properties.getJwt().getIssuerUri();
>         return new RoRJwtDecoderBuilder()//.withIssuer(rorAuth0Issuer)
>                 .withIssuer("http://localhost")
> ```

What is this for?
___
*[`src/main/resources/application.properties` line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlchAev2yO53oISLann:-NlchAev2yO53oISLano:b-8i92kd) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/resources/application.properties#L15)):*
> ```INI
> tiamat.oauth2.resourceserver.auth0.ror.jwt.audience=notinuse
> tiamat.oauth2.resourceserver.auth0.ror.claim.namespace=notinuse
> spring.security.oauth2.resourceserver=localhost
> ```

Separate different prefixes with a line break.
___
*[`src/main/resources/db/migration/V1__Base_version.sql` line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlchPBw3cXVEDeGfg8K:-NlchPBw3cXVEDeGfg8L:b-w26sjv) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/resources/db/migration/V1__Base_version.sql#L21)):*
> ```TSQL
> --
> 
> -- CREATE SCHEMA topology;
> ```

I'd rather delete all commented rows and add a comment how this differs from the upstream.
___
*[`src/test/java/org/rutebanken/tiamat/repository/StopPlaceRepositoryImplTest.java` line 374 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlcgPV136BoW5OkftL5:-NlcgPV136BoW5OkftL6:b-wndbsa) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/test/java/org/rutebanken/tiamat/repository/StopPlaceRepositoryImplTest.java#L374)):*
> ```Java
> 
>     /*
>     * Test disabled due to not using H2 database for testing
> ```

Use `@Ingore` annotation insted.
___
*[`src/test/java/org/rutebanken/tiamat/repository/StopPlaceRepositoryImplTest.java` line  [...]

2023-12-14 14:26 UTC, jarkkoka requested changes
I got the below error message when running `mvn clean verify`:

```
 Could not resolve dependencies for project org.rutebanken:tiamat:jar:0.0.2-SNAPSHOT: The following artifacts could not be resolved: org.entur.helpers:hazelcast4-helper:jar:1.89-SNAPSHOT (absent), org.entur.helpers:organisation:jar:1.89-SNAPSHOT (absent), org.entur.helpers:oauth2:jar:1.89-SNAPSHOT (absent): Could not find artifact org.entur.helpers:hazelcast4-helper:jar:1.89-SNAPSHOT in maven2 (https://repo.maven.apache.org/maven2)
```

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-:-NlchykT6621SmpkxaQp:b54ltg4)* status: 21 of 23 files reviewed, 16 unresolved discussions (waiting on @culka)



<!-- Sent from Reviewable.io -->

2023-12-15 07:18 UTC, culka reviewed
I think you need to run the three `mvn install:install-file` commands in the `Dockerfile`to add the dependencies to your local repository. I'll also add this to the development script.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-:-NlgIP6t9VEUtM2EYJQn:b-wma2t5)* status: 21 of 23 files reviewed, 16 unresolved discussions (waiting on @jarkkoka)

___
*[`.gitignore` line 47 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nlcd8Wl6bq5D2jPh23D:-NlgIQq76FJNluuCaIaU:b-8gwkj9) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/.gitignore#L47)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Hmmm....helper jars in `src/main/resources` folder. Looks very weird. What is really going on here?
</blockquote></details>

This was another possible way to solve the non-mvn jars, but was replaced by using `mvn:install-install-file`. This line was added by mistake and I'll remove it.
___
*[`src/main/java/org/rutebanken/tiamat/config/OAuth2Config.java` line 61 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nlch5dc11SZPsnt9OHG:-Nlg3-ZU923D45e4124z:b1i6h1w) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/java/org/rutebanken/tiamat/config/OAuth2Config.java#L61)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

The configuration needed a proper URL in order to not throw an exception. `localhost`seemed like a safe choice to use.


<!-- Sent from Reviewable.io -->

2023-12-19 14:49 UTC, culka reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 3 of 23 files reviewed, 16 unresolved discussions (waiting on @jarkkoka and @v4)

___
*[`Dockerfile` line 31 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlcdVTt6yFxqbrxeHL3:-Nm0ad6X7nPd2Gg1P027:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/Dockerfile#L31)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This `1.89-SNAPSHOT` version is repeated multiple times. IMO you should introduce an environment variable for it.
</blockquote></details>

Done.
___
*[`Dockerfile` line 40 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nlcdk1XCsL7u-fiLMjH:-Nm0adUdAm9HFHGc3GdK:buxq1zo) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/Dockerfile#L40)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I think we should not use Amazon Corretto. Look what we use in other JVM project repositories.
</blockquote></details>

Changed this to `eclipse-temurin`
___
*[`development.sh` line 56 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nlce9CD7yPwhE9NSpMM:-Nm0bWxJCoX2_E307gbJ:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/development.sh#L56)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`start:deps` is used in our other repositories. IMO the cognitive load would be reduced if we stick to common naming.
</blockquote></details>

Done.
___
*[`development.sh` line 81 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nlce4J775oX1AlWg0Eu:-Nm0bXMa7b2q1hfDgyhM:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/development.sh#L81)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`start:deps` is used in our other repositories. IMO the cognitive load would be reduced if we stick to common naming.
</blockquote></details>

Done.
___
*[`.github/workflows/docker-build.yml` line 17 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nlcecfj77ZzTlip2W02:-Nm0blQCEOgYsaK_q7ft:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/.github/workflows/docker-build.yml#L17)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`@v4` is the latest. Let's change to it.
</blockquote></details>

Done.
___
*[`.github/workflows/run-cypress-tests.yml` line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlcfBrcEqCE9Y97EjG5:-Nm0c2mU8NKphqIQVe6A:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/.github/workflows/run-cypress-tests.yml#L15)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

@v4
</blockquote></details>

Done.
___
*[`src/main/java/org/rutebanken/tiamat/auth/TiamatSecurityConfig.java` line 61 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nlcfags5JHFMGS0bfmC:-Nm0c4-L012xpvAVih_a:b8pq08d) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/java/org/rutebanken/tiamat/auth/TiamatSecurityConfig.java#L61)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Replace tabs with spaces.
</blockquote></details>

Not going to change these affecting compatibility with the upstream fork.
___
*[`src/main/java/org/rutebanken/tiamat/changelog/EntityChangedEventDummyPublisher.java` line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlcfgxbDlK8WHdl3RuK:-Nm0cHvH1pcogta5xeck:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/java/org/rutebanken/tiamat/changelog/EntityChangedEventDummyPublisher.java#L15)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Uppercase: `log` -> `LOG`
</blockquote></details>

Done.
___
*[`src/main/java/org/rutebanken/tiamat/changelog/EntityChangedEventPubSubPublisher.java` line 31 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlcghtG3N2ahekFPowc:-Nm1VlhAB9Ifax400gnB:b-whig9c) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/java/org/rutebanken/tiamat/changelog/EntityChangedEventPubSubPublisher.java#L31)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Maybe this whole class could be removed.
</blockquote></details>

Removing works as well. :+1: 
___
*[`src/main/java/org/rutebanken/tiamat/config/GooglePubSubConfig.java` line 12 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlcgqAc2Woe0h9nH0Td:-Nm1Vqpb0DJR5F1nBLKW:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/java/org/rutebanken/tiamat/config/GooglePubSubConfig.java#L12)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Couldn't you delete the whole class
</blockquote></details>

Done.
___
*[`src/main/resources/application.properties` line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlchAev2yO53oISLann:-Nm1WI4g8a2PxCsy2HEV:b1u5x0k) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/resources/application.properties#L15)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Separate different prefixes with a line break.
</blockquote></details>

Reformatted the whole file to group prefixes together
___
*[`src/main/resources/db/migration/V1__Base_version.sql` line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlchPBw3cXVEDeGfg8K:-Nm1XRDSA9LMg9z1_XbB:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/resources/db/migration/V1__Base_version.sql#L21)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I'd rather delete all commented rows and add a comment how this differs from the upstream.
</blockquote></details>

Done.
___
*[`src/test/java/org/rutebanken/tiamat/repository/StopPlaceRepositoryImplTest.java` line 374 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlcgPV136BoW5OkftL5:-Nm1YJsa-X14npMJVVxA:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/test/java/org/rutebanken/tiamat/repository/StopPlaceRepositoryImplTest.java#L374)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Use `@Ingore` annotation insted.
</blockquote></details>

Done.
___
*[`src/test/java/org/rutebanken/tiamat/repository/StopPlaceRepositoryImplTest.java` line 410 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlcgLtH86jv8NsIBiWW:-Nm1YKE_3I484iK4Pbpp:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/test/java/org/rutebanken/tiamat/repository/StopPlaceRepositoryImplTest.java#L410)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Use `@Ingore` annotation insted.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-19 18:10 UTC, jarkkoka requested changes
Ok, thanks. That piece of information should definitely be in the `README`. Actually, you should add them to `development.sh`.

> Reviewed 2 of 20 files at r3, 17 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-:-Nm2FZFfEiIvHKr2M1RB:brgfc5e)* status: 22 of 23 files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`src/main/java/org/rutebanken/tiamat/config/OAuth2Config.java` line 61 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nlch5dc11SZPsnt9OHG:-Nm29c38AgGCB_qh2n8y:bitimac) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/java/org/rutebanken/tiamat/config/OAuth2Config.java#L61)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

The configuration needed a proper URL in order to not throw an exception. `localhost`seemed like a safe choice to use.
</blockquote></details>

I'd rather have the flexibility to change the value from this hard-coded dummy one to something else without needing to change the code. Consider adding it as a configurable property since there already are injected two values into this method (like `tiamat.oauth2.resourceserver.auth0.ror.jwt.issuer`).
___
*[`src/main/resources/db/migration/V1__Base_version.sql` line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlchPBw3cXVEDeGfg8K:-Nm2G1XN2sfwCQIWH0EU:bs251ci) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/resources/db/migration/V1__Base_version.sql#L21)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'd still like to have a comment here telling that some schema and extension creation is deleted when compared to the upstream.


<!-- Sent from Reviewable.io -->

2023-12-19 18:16 UTC, jarkkoka requested changes
Even after running these `mvn install:install-file` commands (from `Dockerfile`) I get a build error when I run `mvn clean verify`.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-:-Nm2HTwO5sUh45kSUJ_q:b-9xdpub)* status: 22 of 23 files reviewed, 2 unresolved discussions (waiting on @culka)



<!-- Sent from Reviewable.io -->

2023-12-20 08:28 UTC, jarkkoka requested changes
Ok, it turns out that the previous error was caused by Java 11 vs 17 class file differences.

However, now there are a lot of "Connection refused" errors while running tests (`mvn clean verify`). The tests seem to fail because of not able to connect to the database.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-:-Nm5Kaee8BBohXsYN0qb:b-s3rn5r)* status: 22 of 23 files reviewed, 2 unresolved discussions (waiting on @culka)



<!-- Sent from Reviewable.io -->

2023-12-20 12:02 UTC, culka reviewed
There was a bad configuration in the test `application.properties`, they should work now.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-:-Nm6368F4GKfc4dyNMdo:b-yy2y9d)* status: 17 of 25 files reviewed, 2 unresolved discussions (waiting on @jarkkoka)

___
*[`src/main/java/org/rutebanken/tiamat/config/OAuth2Config.java` line 61 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nlch5dc11SZPsnt9OHG:-Nm65m161BnzeRYvP_o1:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/java/org/rutebanken/tiamat/config/OAuth2Config.java#L61)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I'd rather have the flexibility to change the value from this hard-coded dummy one to something else without needing to change the code. Consider adding it as a configurable property since there already are injected two values into this method (like `tiamat.oauth2.resourceserver.auth0.ror.jwt.issuer`).
</blockquote></details>

Done.
___
*[`src/main/resources/db/migration/V1__Base_version.sql` line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NlchPBw3cXVEDeGfg8K:-Nm634-LCUZ-9tWJO48k:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/b1f459a16b7118a55180fe92dfddca7c4d36d1c9/src/main/resources/db/migration/V1__Base_version.sql#L21)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I'd still like to have a comment here telling that some schema and extension creation is deleted when compared to the upstream.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-20 12:30 UTC, jarkkoka requested changes
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: all files reviewed, 5 unresolved discussions (waiting on @culka)

___
*[`README.md` line 12 at r5](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nm6Bmq25BwJS1Z9Z6Km:-Nm6Bmq25BwJS1Z9Z6Kn:b-osbsr6) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/0a86880bf89d83d369f08c694e6690c117cbb6ab/README.md#L12)):*
> ```Markdown
> ### Dependencies
> Tiamat uses helper libraries which are not available at any Maven repository, but they are included in this git repository.
> You need to install the local versions of the helper libraries, this can be done using the development script: `.development.sh libs`
> ```

Fix to: `./development.sh` (the slash character is missing).
___
*[`.github/workflows/run-java-tests.yml` line 23 at r5](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nm6BVMK-2QFbuIwbsnW:-Nm6BVMK-2QFbuIwbsnX:b-j6m38t) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/0a86880bf89d83d369f08c694e6690c117cbb6ab/.github/workflows/run-java-tests.yml#L23)):*
> ```YAML
> 
>       - name: Start dependencies (blocking until up)
>         run: ./development.sh start:deps
> ```

I think you should install the helpers libraries as well before running tests.
___
*[`.github/workflows/run-java-tests.yml` line 44 at r5](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nm6Aesw34hcwret0nBE:-Nm6Aesx4PE7F1YE4bL3:bwu1gqq) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/0a86880bf89d83d369f08c694e6690c117cbb6ab/.github/workflows/run-java-tests.yml#L44)):*
> ```YAML
>           # create mandatory Maven configuration file for runner user
>           RUNNER_USERNAME=$(whoami)
>           touch ./profiles/dev/config.${RUNNER_USERNAME}.properties
> ```

It seems to me that there is no `./profiles/dev/` directory in the repository. Have you forgotten to commit it?
___
*[`src/main/java/org/rutebanken/tiamat/config/OAuth2Config.java` line 61 at r5](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nm6AuMY0Sa8E08eu3BM:-Nm6AuMY0Sa8E08eu3BN:b-mp68y9) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/0a86880bf89d83d369f08c694e6690c117cbb6ab/src/main/java/org/rutebanken/tiamat/config/OAuth2Config.java#L61)):*
> ```Java
>     ) {
> 
>         //String rorAuth0Issuer = properties.getJwt().getIssuerUri();
> ```

IMO this line can now be removed since the actual value is injected from elsewhere.


<!-- Sent from Reviewable.io -->

2023-12-20 12:32 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: all files reviewed, 8 unresolved discussions (waiting on @culka)

___
*[`.github/workflows/docker-build.yml` line 23 at r5](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nm6CXBDEI45yTlmY675:-Nm6CXBDEI45yTlmY676:b32wxu) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/0a86880bf89d83d369f08c694e6690c117cbb6ab/.github/workflows/docker-build.yml#L23)):*
> ```YAML
> 
>       - name: Set up QEMU
>         uses: docker/setup-qemu-action@v2
> ```

v3
___
*[`.github/workflows/docker-build.yml` line 28 at r5](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nm6CTwl0Pfl0lwsraNN:-Nm6CTwl0Pfl0lwsraNO:b32wxu) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/0a86880bf89d83d369f08c694e6690c117cbb6ab/.github/workflows/docker-build.yml#L28)):*
> ```YAML
> 
>       - name: Set up Docker Buildx
>         uses: docker/setup-buildx-action@v2
> ```

v3
___
*[`.github/workflows/docker-build.yml` line 31 at r5](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nm6CRt084pr-ge4w17X:-Nm6CRt084pr-ge4w17Y:b32wxu) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/0a86880bf89d83d369f08c694e6690c117cbb6ab/.github/workflows/docker-build.yml#L31)):*
> ```YAML
> 
>       - name: Login to Docker Hub
>         uses: docker/login-action@v2
> ```

v3


<!-- Sent from Reviewable.io -->

2023-12-20 13:03 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: all files reviewed, 9 unresolved discussions (waiting on @culka)

___
*[`.github/workflows/run-java-tests.yml` line 26 at r5](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nm6JgRE72d31uTZ-j-A:-Nm6JgRE72d31uTZ-j-B:b32wxv) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/0a86880bf89d83d369f08c694e6690c117cbb6ab/.github/workflows/run-java-tests.yml#L26)):*
> ```YAML
> 
>       - name: Set up JDK 11
>         uses: actions/setup-java@v3
> ```

v4


<!-- Sent from Reviewable.io -->

2023-12-20 13:16 UTC, culka reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 20 of 25 files reviewed, 9 unresolved discussions (waiting on @jarkkoka)

___
*[`README.md` line 12 at r5](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nm6Bmq25BwJS1Z9Z6Km:-Nm6LGK44WS2yYMOP9br:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/0a86880bf89d83d369f08c694e6690c117cbb6ab/README.md#L12)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Fix to: `./development.sh` (the slash character is missing).
</blockquote></details>

Done.
___
*[`.github/workflows/docker-build.yml` line 23 at r5](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nm6CXBDEI45yTlmY675:-Nm6LCpt6MglJz8UG8DZ:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/0a86880bf89d83d369f08c694e6690c117cbb6ab/.github/workflows/docker-build.yml#L23)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

v3
</blockquote></details>

Done.
___
*[`.github/workflows/docker-build.yml` line 28 at r5](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nm6CTwl0Pfl0lwsraNN:-Nm6LD54Cib3ytSJiF5V:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/0a86880bf89d83d369f08c694e6690c117cbb6ab/.github/workflows/docker-build.yml#L28)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

v3
</blockquote></details>

Done.
___
*[`.github/workflows/docker-build.yml` line 31 at r5](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nm6CRt084pr-ge4w17X:-Nm6LDHR4RV_WefyWqnX:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/0a86880bf89d83d369f08c694e6690c117cbb6ab/.github/workflows/docker-build.yml#L31)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

v3
</blockquote></details>

Done.
___
*[`.github/workflows/run-java-tests.yml` line 23 at r5](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nm6BVMK-2QFbuIwbsnW:-Nm6KzVwDKh64p8OhVxI:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/0a86880bf89d83d369f08c694e6690c117cbb6ab/.github/workflows/run-java-tests.yml#L23)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I think you should install the helpers libraries as well before running tests.
</blockquote></details>

Done.
___
*[`.github/workflows/run-java-tests.yml` line 26 at r5](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nm6JgRE72d31uTZ-j-A:-Nm6L0lS9CvoyoGbdpbd:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/0a86880bf89d83d369f08c694e6690c117cbb6ab/.github/workflows/run-java-tests.yml#L26)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

v4
</blockquote></details>

Done.
___
*[`.github/workflows/run-java-tests.yml` line 44 at r5](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nm6Aesw34hcwret0nBE:-Nm6L1xyCbKiSRur13VR:b-8r8my9) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/0a86880bf89d83d369f08c694e6690c117cbb6ab/.github/workflows/run-java-tests.yml#L44)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

It seems to me that there is no `./profiles/dev/` directory in the repository. Have you forgotten to commit it?
</blockquote></details>

This is not currently used in Tiamat, probably should be added later.
___
*[`src/main/java/org/rutebanken/tiamat/config/OAuth2Config.java` line 61 at r5](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nm6AuMY0Sa8E08eu3BM:-Nm6LKaw8NNgdWF-qIYn:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/0a86880bf89d83d369f08c694e6690c117cbb6ab/src/main/java/org/rutebanken/tiamat/config/OAuth2Config.java#L61)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO this line can now be removed since the actual value is injected from elsewhere.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-11 12:56 UTC, jarkkoka requested changes
> Reviewed 4 of 5 files at r6, 25 of 41 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 29 of 45 files reviewed, 4 unresolved discussions (waiting on @culka)

___
*[`pom.xml` line 95 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nns_GdpD7sx7fgYRu05:-Nns_GdpD7sx7fgYRu06:b-13kge4) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L95)):*
> ```XML
>             sync, and fail fast if incompatibilities -->
>         <netex-java-model.version>1.0.14</netex-java-model.version>
>         <hazelcast-helper.version>1.0.62</hazelcast-helper.version>
> ```

Should this actually be `1.89-SNAPSHOT`?
___
*[`pom.xml` line 101 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnsa0gV4F1UaUlAYFth:-Nnsa0gV4F1UaUlAYFti:b22e7yr) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L101)):*
> ```XML
> 
>         <javax-jms.version>2.0.1</javax-jms.version>
>         <jts-core.version>1.19.0</jts-core.version>
> ```

This seems not be effective.
___
*[`pom.xml` line 144 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nns_jVtB8acn61M6RSR:-Nns_jVtB8acn61M6RSS:b-ooj9x0) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L144)):*
> ```XML
>             <dependency>
>                 <groupId>org.entur.helpers</groupId>
>                 <artifactId>hazelcast4-helper</artifactId>
> ```

The first instance of `hazelcast4-helper` artifact.
___
*[`pom.xml` line 254 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nns_uLz2DXLB_nxv0Wj:-Nns_uLz2DXLB_nxv0Wk:bf56etp) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L254)):*
> ```XML
>         </dependency>
>         <dependency>
>             <groupId>org.entur.helpers</groupId>
> ```

The second instance of `hazelcast4-helper` artifact with different version.


<!-- Sent from Reviewable.io -->

2024-01-11 13:11 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 29 of 45 files reviewed, 5 unresolved discussions (waiting on @culka)

___
*[`pom.xml` line 68 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnsdKbP3fSIBoH5eEy-:-NnsdKbP3fSIBoH5eEy0:b-lv01pj) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L68)):*
> ```XML
>         <spring-boot.version>2.7.18</spring-boot.version>
>         <spring.security.version>5.3.5.RELEASE</spring.security.version>
>         <postgresql.version>42.2.4</postgresql.version>
> ```

`postgresql.version` can be removed and let Spring Boot set version implicitly.


<!-- Sent from Reviewable.io -->

2024-01-11 13:15 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 29 of 45 files reviewed, 8 unresolved discussions (waiting on @culka)

___
*[`pom.xml` line 488 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnseFN2ErI-JLEkV23f:-NnseNkN4mkmoB3--PA3:b-1aphk7) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L488)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Tests pass without `gt-jts-wrapper`. This can possibly be removed.
</blockquote></details>

It seems like an old library that is not used anymore in more recent GeoTools versions.


<!-- Sent from Reviewable.io -->

2024-01-11 13:36 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 29 of 45 files reviewed, 14 unresolved discussions (waiting on @culka)

___
*[`pom.xml` line 21 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnsh6MB9Q0rIlX_lm6N:-Nnsh6MC8g5p2yngUKZy:btzg5cv) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L21)):*
> ```XML
>     <modelVersion>4.0.0</modelVersion>
> 
>     <groupId>org.rutebanken</groupId>
> ```

Add Spring Boot as parent:
```xml
<parent>  
    <groupId>org.springframework.boot</groupId>  
    <artifactId>spring-boot-starter-parent</artifactId>  
    <version>2.7.18</version>  
    <relativePath/> <!-- lookup parent from repository -->  
</parent>
```
___
*[`pom.xml` line 87 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnsiSmR08nqVn17Bbh6:-NnsgBvN89e7r2qKa8-c:b-vn860v) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L87)):*
> ```XML
>         <hazelcast-hibernate53.version>2.1.1</hazelcast-hibernate53.version>
>         <groovy-all.version>3.0.19</groovy-all.version>
>         <jaxb-version>2.3.0.1</jaxb-version>
> ```

I think `jaxb-version` property can be removed. Use `javax-jaxb.version` instead below (within dependencies) instead.
___
*[`pom.xml` line 137 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnshDdb7J00ChBrOn8u:-NnshDdb7J00ChBrOn8v:bjcqots) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L137)):*
> ```XML
>                 <groupId>org.springframework.boot</groupId>
>                 <artifactId>spring-boot-dependencies</artifactId>
>                 <version>${spring-boot.version}</version>
> ```

Remove `spring-boot-dependencies` as a dependency because it should be set as a parent (to inherit version properties). This is done in our other repositories.
___
*[`pom.xml` line 223 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnsinW-91WuNb_baykU:-NnsinW-91WuNb_baykV:b-4dn20l) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L223)):*
> ```XML
>             <groupId>com.sun.xml.bind</groupId>
>             <artifactId>jaxb-impl</artifactId>
>             <version>${jaxb-version}</version>
> ```

`jaxb-version` could be replaced with `javax-jaxb.version` which is inherited from Spring Boot parent.
___
*[`pom.xml` line 226 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnsiiLv81Rrqs7n-7TV:-NnsiiLv81Rrqs7n-7TW:b-putfuj) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L226)):*
> ```XML
>         </dependency>
>         <dependency>
>             <groupId>com.sun.xml.bind</groupId>
> ```

IMO `jaxb-core` can be removed. Tests pass without it.
___
*[`pom.xml` line 233 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnsiv0i8g2aJAMUnsm7:-Nnsiv0i8g2aJAMUnsm8:b-4dn20l) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L233)):*
> ```XML
>             <groupId>com.sun.xml.bind</groupId>
>             <artifactId>jaxb-xjc</artifactId>
>             <version>${jaxb-version}</version>
> ```

`jaxb-version` could be replaced with `javax-jaxb.version` which is inherited from Spring Boot parent.


<!-- Sent from Reviewable.io -->

2024-01-11 13:36 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 29 of 45 files reviewed, 15 unresolved discussions (waiting on @culka)

___
*[`pom.xml` line 66 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnsjFN52ZDj-VztCJ3n:-NnsjFN52ZDj-VztCJ3o:bqladrb) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L66)):*
> ```XML
>         <plexus.compiler.javac.version>2.8.8</plexus.compiler.javac.version>
>         <spring-boot-plugin.version>2.7.18</spring-boot-plugin.version>
>         <spring-boot.version>2.7.18</spring-boot.version>
> ```

`spring-boot.version` can be removed when using Spring Boot as parent.


<!-- Sent from Reviewable.io -->

2024-01-11 13:37 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 29 of 45 files reviewed, 16 unresolved discussions (waiting on @culka)

___
*[`pom.xml` line 82 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnsjNVo2PcylL6kwj6J:-NnsjNVo2PcylL6kwj6K:bg6wvye) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L82)):*
> ```XML
>         <commons.lang3.version>3.7</commons.lang3.version>
>         <orika-core.version>1.5.4</orika-core.version>
>         <guava.version>30.1.1-jre</guava.version>
> ```

Guava can be updated to `33.0.0-jre`


<!-- Sent from Reviewable.io -->

2024-01-11 13:59 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 29 of 45 files reviewed, 18 unresolved discussions (waiting on @culka)

___
*[`pom.xml` line 105 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnsoN2O-v8zbic9Nw0S:-NnsoN2O-v8zbic9Nw0T:b-w5hpm3) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L105)):*
> ```XML
>         <maven-surefire-plugin.version>3.0.0-M6</maven-surefire-plugin.version>
>         <maven-antrun-plugin.version>3.0.0</maven-antrun-plugin.version>
>         <argLine></argLine>
> ```

IMO `argLine` does not belong to inside `properties` element.


<!-- Sent from Reviewable.io -->

2024-01-11 14:01 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 29 of 45 files reviewed, 19 unresolved discussions (waiting on @culka)

___
*[`pom.xml` line 260 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnsoiej2j9EtpvVWCtZ:-Nnsoiej2j9EtpvVWCt_:b-s6tbvb) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L260)):*
> ```XML
> 
>         <dependency>
>             <groupId>org.entur.helpers</groupId>
> ```

These two artifacts (`org.entur.helpers.organisation` and `org.entur.helpers.oauth2`) appear twice as well.


<!-- Sent from Reviewable.io -->

2024-01-11 14:07 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 29 of 45 files reviewed, 22 unresolved discussions (waiting on @culka)

___
*[`pom.xml` line 67 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnsq4Oy7ZPEwltosCvj:-Nnsq4Oy7ZPEwltosCvk:b-pvhxxu) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L67)):*
> ```XML
>         <spring-boot-plugin.version>2.7.18</spring-boot-plugin.version>
>         <spring-boot.version>2.7.18</spring-boot.version>
>         <spring.security.version>5.3.5.RELEASE</spring.security.version>
> ```

`spring.security.version` can be removed because it comes implicitly with Spring Boot parent.
___
*[`pom.xml` line 382 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnsqDOB4XvOgjd9Og8z:-NnsqDOB4XvOgjd9Og9-:bgg8r6b) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L382)):*
> ```XML
>             <groupId>org.springframework.security</groupId>
>             <artifactId>spring-security-config</artifactId>
>             <version>${spring.security.version}</version>
> ```

Explicit `version` element referencing `spring.security.version` property can be removed because the version comes implicitly with Spring Boot parent.
___
*[`pom.xml` line 388 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnsqQ4J2XaCDXK2uyPk:-NnsqQ4J2XaCDXK2uyPl:bgg8r6b) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L388)):*
> ```XML
>             <groupId>org.springframework.security</groupId>
>             <artifactId>spring-security-web</artifactId>
>             <version>${spring.security.version}</version>
> ```

Explicit `version` element referencing `spring.security.version` property can be removed because the version comes implicitly with Spring Boot parent.


<!-- Sent from Reviewable.io -->

2024-01-11 14:13 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 29 of 45 files reviewed, 24 unresolved discussions (waiting on @culka)

___
*[`pom.xml` line 79 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnsrbjw7YjQt1h-mbPq:-Nnsrbjw7YjQt1h-mbPr:b-k5vkdg) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L79)):*
> ```XML
>         <javax.el.version>3.0.0</javax.el.version>
>         <com.h2database.version>1.4.197</com.h2database.version>
>         <hikariCP.version>3.2.0</hikariCP.version>
> ```

The `hikariCP.version` property can be removed, because the Hikari version comes implicitly with Spring Boot parent.
___
*[`pom.xml` line 443 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnsrQDb2JP0qrmZPUR4:-NnsrQDb2JP0qrmZPUR5:b-q4rgia) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L443)):*
> ```XML
>             <groupId>com.zaxxer</groupId>
>             <artifactId>HikariCP</artifactId>
>             <version>${hikariCP.version}</version>
> ```

The `version` element. for HikariCP (referencing `hikariCP.version`) can be removed, because the version comes implicitly with Spring Boot parent.


<!-- Sent from Reviewable.io -->

2024-01-11 14:15 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 29 of 45 files reviewed, 26 unresolved discussions (waiting on @culka)

___
*[`pom.xml` line 297 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnss8741jlChQUNH2-z:-Nnss8741jlChQUNH20-:bxgvqcp) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L297)):*
> ```XML
>             <groupId>ch.qos.logback</groupId>
>             <artifactId>logback-classic</artifactId>
>             <version>${logback.version}</version>
> ```

Explicit `version` element referencing `logback.version` property can be removed because the version comes implicitly with Spring Boot parent.
___
*[`pom.xml` line 302 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnssBn7D6NnMYROQe87:-NnssBn7D6NnMYROQe88:bxgvqcp) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L302)):*
> ```XML
>             <groupId>ch.qos.logback</groupId>
>             <artifactId>logback-core</artifactId>
>             <version>${logback.version}</version>
> ```

Explicit `version` element referencing `logback.version` property can be removed because the version comes implicitly with Spring Boot parent.


<!-- Sent from Reviewable.io -->

2024-01-11 14:19 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 29 of 45 files reviewed, 28 unresolved discussions (waiting on @culka)

___
*[`pom.xml` line 65 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnsso2L0bl48vsRRXJu:-Nnsso2L0bl48vsRRXJv:b-2vpf0m) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L65)):*
> ```XML
>         <maven.compiler.plugin.version>3.8.1</maven.compiler.plugin.version>
>         <plexus.compiler.javac.version>2.8.8</plexus.compiler.javac.version>
>         <spring-boot-plugin.version>2.7.18</spring-boot-plugin.version>
> ```

`spring-boot.plugin.version` can be removed when using Spring Boot as parent.
___
*[`pom.xml` line 665 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnst00TC6mh2yMwiDcH:-Nnst00TC6mh2yMwiDcI:ba0xxx4) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L665)):*
> ```XML
>                 <groupId>org.springframework.boot</groupId>
>                 <artifactId>spring-boot-maven-plugin</artifactId>
>                 <version>${spring-boot-plugin.version}</version>
> ```

Explicit `version` element (referencing `spring-boot.plugin.version` property) can be removed, because the version comes implicitly set when using Spring Boot as parent.


<!-- Sent from Reviewable.io -->

2024-01-11 14:39 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 29 of 45 files reviewed, 29 unresolved discussions (waiting on @culka)

___
*[`pom.xml` line 353 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnsxd-a9ZpaID5oUM4k:-Nnsxd-a9ZpaID5oUM4l:b4awhpv) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L353)):*
> ```XML
>             <exclusions>
>                 <exclusion>
>                     <groupId>org.apache.tomcat</groupId>
> ```

It seems to be that both of these exclusions (`tomcat-jdbc` and `hibernate-core`) are ineffective and hence can be removed.


<!-- Sent from Reviewable.io -->

2024-01-11 14:45 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 29 of 45 files reviewed, 31 unresolved discussions (waiting on @culka)

___
*[`pom.xml` line 100 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnsykff1pDwSPAhVxVO:-Nnsykff1pDwSPAhVxVP:bon62j6) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L100)):*
> ```XML
>         <entur.helpers.version>1.89-SNAPSHOT</entur.helpers.version>
> 
>         <javax-jms.version>2.0.1</javax-jms.version>
> ```

`javax-jms.version` property is not needed, because the version comes implicitly with Spring Boot parent.
___
*[`pom.xml` line 238 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnsywfc4knKH0n2XmQC:-Nnsywfc4knKH0n2XmQD:b-ji598m) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L238)):*
> ```XML
>             <groupId>javax.jms</groupId>
>             <artifactId>javax.jms-api</artifactId>
>             <version>${javax-jms.version}</version>
> ```

Explicit `version` element (referencing `javax-jms.version` property) can be removed because the version comes implicitly with Spring Boot parent.


<!-- Sent from Reviewable.io -->

2024-01-11 15:01 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 29 of 45 files reviewed, 33 unresolved discussions (waiting on @culka)

___
*[`pom.xml` line 78 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnt1X0FBUre9mn7CcYM:-Nnt1X0FBUre9mn7CcYN:b-x7h111) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L78)):*
> ```XML
>         <assertj-core.version>3.10.0</assertj-core.version>
>         <javax.el.version>3.0.0</javax.el.version>
>         <com.h2database.version>1.4.197</com.h2database.version>
> ```

The `com.h2database.version` property can be removed, because a more recent H2 version comes implicitly with Spring Boot parent.
___
*[`pom.xml` line 437 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnt1fdz6HPKdYyCOhSr:-Nnt1fdz6HPKdYyCOhSs:b-ff23i0) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L437)):*
> ```XML
>             <groupId>com.h2database</groupId>
>             <artifactId>h2</artifactId>
>             <version>${com.h2database.version}</version>
> ```

The `version` element for H2 (referencing `com.h2database.version`) can be removed, because the version comes implicitly with Spring Boot parent.


<!-- Sent from Reviewable.io -->

2024-01-12 07:29 UTC, culka reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 29 of 45 files reviewed, 33 unresolved discussions (waiting on @jarkkoka)

___
*[`pom.xml` line 21 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnsh6MB9Q0rIlX_lm6N:-NnwZkeFCZYBsCBYA69h:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L21)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Add Spring Boot as parent:
```xml
<parent>  
    <groupId>org.springframework.boot</groupId>  
    <artifactId>spring-boot-starter-parent</artifactId>  
    <version>2.7.18</version>  
    <relativePath/> <!-- lookup parent from repository -->  
</parent>
```
</blockquote></details>

Done.
___
*[`pom.xml` line 65 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnsso2L0bl48vsRRXJu:-NnwZkxC81AuPY0qM39O:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L65)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`spring-boot.plugin.version` can be removed when using Spring Boot as parent.
</blockquote></details>

Done.
___
*[`pom.xml` line 66 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnsjFN52ZDj-VztCJ3n:-NnwZl898JAoPmmTUxjQ:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L66)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`spring-boot.version` can be removed when using Spring Boot as parent.
</blockquote></details>

Done.
___
*[`pom.xml` line 67 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnsq4Oy7ZPEwltosCvj:-NnwZlWA3U7z0lWEkJr2:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L67)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`spring.security.version` can be removed because it comes implicitly with Spring Boot parent.
</blockquote></details>

Done.
___
*[`pom.xml` line 68 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnsdKbP3fSIBoH5eEy-:-NnwZllV694gpagHHf_m:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L68)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`postgresql.version` can be removed and let Spring Boot set version implicitly.
</blockquote></details>

Done.
___
*[`pom.xml` line 70 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnsduQmBuYNW90VqDLN:-NnwZlyIE2nkrRTTwdLI:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L70)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO GeoTools could be updated to the version `29.1` and remove `gt-jts-wrapper` library which seems obsolete nowadays.
</blockquote></details>

Done.
___
*[`pom.xml` line 78 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnt1X0FBUre9mn7CcYM:-NnwZmJo9CrT9Llj1310:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L78)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

The `com.h2database.version` property can be removed, because a more recent H2 version comes implicitly with Spring Boot parent.
</blockquote></details>

Done.
___
*[`pom.xml` line 79 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnsrbjw7YjQt1h-mbPq:-NnwZmUV9PRsmExYN1b3:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L79)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

The `hikariCP.version` property can be removed, because the Hikari version comes implicitly with Spring Boot parent.
</blockquote></details>

Done.
___
*[`pom.xml` line 82 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnsjNVo2PcylL6kwj6J:-NnwZme88uKYdaouqvZT:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L82)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Guava can be updated to `33.0.0-jre`
</blockquote></details>

Done.
___
*[`pom.xml` line 87 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnsiSmR08nqVn17Bbh6:-NnwZn2r7ADM6ogZZUMR:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L87)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I think `jaxb-version` property can be removed. Use `javax-jaxb.version` instead below (within dependencies) instead.
</blockquote></details>

Done.
___
*[`pom.xml` line 95 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nns_GdpD7sx7fgYRu05:-NnwZnDqEyLSbJkmtvyb:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L95)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Should this actually be `1.89-SNAPSHOT`?
</blockquote></details>

Done.
___
*[`pom.xml` line 100 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnsykff1pDwSPAhVxVO:-NnwZnQLCjcBFKOEtlwI:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L100)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`javax-jms.version` property is not needed, because the version comes implicitly with Spring Boot parent.
</blockquote></details>

Done.
___
*[`pom.xml` line 101 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nnsa0gV4F1UaUlAYFth:-NnwZnwb0oG2OPu0jZ7u:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L101)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This seems not be effective.
</blockquote></details>

Done.
___
*[`pom.xml` line 105 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnsoN2O-v8zbic9Nw0S:-NnwZo8_2ex9YqZ-Fx_H:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L105)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO `argLine` does not belong to inside `properties` element.
</blockquote></details>

Done.
___
*[`pom.xml` line 107 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnsmpuiDk8-_DzwFVYd:-NnwZoII5OvrDFfvuFHT:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L107)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This explicit `logback.version` can be removed because the more recent version `1.2.12` comes automagically (implicitly) with Spring Boot parent.
</blockquote></details>

Done.
___
*[`pom.xml` line 137 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NnshDdb7J00ChBrOn8u:-NnwZofV96RUU0XRlPI-:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/8cb9a94bc6330fd652fe15766c3218f1fe4798d7/pom.xml#L137)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Remove `spring-boot-dependencies` as a dependency because it should be set as a parent (to inherit version properties). This is done in our other repositories.
</blockquote></details>

Done.
___
*[`pom.xml` line 144 at r8](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-Nns_jVtB8acn61M6RSR:-NnwZowd4dXtJxXXurZk:b-896fix) ([raw file](https://github.com/h [...]

2024-01-18 08:24 UTC, jarkkoka reviewed
> Reviewed 7 of 41 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 37 of 45 files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`src/test/resources/application.properties` line 47 at r9](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NoQeSXW3KNSDOzbuauI:-NoQeSXW3KNSDOzbuauJ:b2wuzx3) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/9dcc830ea49fd32106145e070cfc9e45df49c171/src/test/resources/application.properties#L47)):*
> ```INI
> server.port=1888
> 
> spring.profiles.active=geodb,activemq
> ```

Does `geodb` being marked as active Spring profile in tests interfere someway? Since in `GeoDBDataSourceConfig` class there is now `@Profile("disabled")`


<!-- Sent from Reviewable.io -->

2024-01-18 08:51 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 37 of 45 files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`src/main/java/org/rutebanken/tiamat/config/GeoDBDataSourceConfig.java` line 26 at r9](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NoQkerV4w-ob9mwUjfj:-NoQkerV4w-ob9mwUjfk:b9ucbfm) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/9dcc830ea49fd32106145e070cfc9e45df49c171/src/main/java/org/rutebanken/tiamat/config/GeoDBDataSourceConfig.java#L26)):*
> ```Java
> 
> @Configuration
> @Profile("disabled") // Disabled for Jore4
> ```

IMO the name of this profile should not be changed. Instead, the profile should be disabled by just not including it in active profiles.


<!-- Sent from Reviewable.io -->

2024-01-18 13:17 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 37 of 45 files reviewed, 4 unresolved discussions (waiting on @culka)

___
*[`-- commits` line 84 at r9](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NoRhGRpCEqi0EumNzjv):*
"version"
___
*[`-- commits` line 92 at r9](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NoRhDmE0FMEylT6cxey):*
"version"


<!-- Sent from Reviewable.io -->

2024-01-18 13:23 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 37 of 45 files reviewed, 6 unresolved discussions (waiting on @culka)

___
*[`src/main/resources/application.properties` line 7 at r9](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NoRj1YXEEHqLLItZ5ar:-NoRj1YXEEHqLLItZ5as:b-k039im) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/9dcc830ea49fd32106145e070cfc9e45df49c171/src/main/resources/application.properties#L7)):*
> ```INI
> 
> spring.datasource.platform=postgres
> spring.database.driverClassName=org.postgresql.Driver
> ```

I think this should be `spring.datasource.driver-class-name`.

Take a look at:

https://docs.spring.io/spring-boot/docs/2.7.18/reference/html/application-properties.html#application-properties.data.spring.datasource.driver-class-name.
___
*[`src/test/resources/application.properties` line 34 at r9](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NoRjUu948b_vw_XauTU:-NoRjUu948b_vw_XauTV:b-k039im) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/9dcc830ea49fd32106145e070cfc9e45df49c171/src/test/resources/application.properties#L34)):*
> ```INI
> spring.datasource.password=${tiamat.db.password:tiamatpassword}
> spring.datasource.url=${tiamat.db.url:jdbc:postgresql://localhost:6432/stopdb}
> spring.database.driverClassName=org.postgresql.Driver
> ```

I think this should be `spring.datasource.driver-class-name`.

Take a look at:

https://docs.spring.io/spring-boot/docs/2.7.18/reference/html/application-properties.html#application-properties.data.spring.datasource.driver-class-name.


<!-- Sent from Reviewable.io -->

2024-01-18 13:27 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 37 of 45 files reviewed, 7 unresolved discussions (waiting on @culka)

___
*[`src/main/resources/application.properties` line 6 at r9](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NoRkFj5CjVJMlqNtD9i:-NoRkFj5CjVJMlqNtD9j:br05n77) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/9dcc830ea49fd32106145e070cfc9e45df49c171/src/main/resources/application.properties#L6)):*
> ```INI
> spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect
> 
> spring.datasource.platform=postgres
> ```

`spring.datasource.platform` seems to be deprecated (according to IDEA).


<!-- Sent from Reviewable.io -->

2024-01-18 13:30 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 37 of 45 files reviewed, 8 unresolved discussions (waiting on @culka)

___
*[`src/main/resources/application.properties` line 11 at r9](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NoRkviH4pRJTgXLPGBC:-NoRkviH4pRJTgXLPGBD:b-sc1ipi) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/9dcc830ea49fd32106145e070cfc9e45df49c171/src/main/resources/application.properties#L11)):*
> ```INI
> spring.datasource.username=${tiamat.db.username:tiamat}
> spring.datasource.password=${tiamat.db.password:tiamatpassword}
> spring.datasource.initializationFailFast=false
> ```

IDEA says about `spring.datasource.initializationFailFast` that it is not resolved.


<!-- Sent from Reviewable.io -->

2024-01-18 13:32 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8)* status: 37 of 45 files reviewed, 9 unresolved discussions (waiting on @culka)

___
*[`src/main/resources/application.properties` line 15 at r9](https://reviewable.io/reviews/hsldevcom/jore4-tiamat/8#-NoRlIAiC9uch1BhRmzN:-NoRlIAiC9uch1BhRmzO:biu4jqy) ([raw file](https://github.com/hsldevcom/jore4-tiamat/blob/9dcc830ea49fd32106145e070cfc9e45df49c171/src/main/resources/application.properties#L15)):*
> ```INI
> spring.profiles.active=local-blobstore,activemq
> 
> spring.security.oauth2.resourceserver=localhost
> ```

This `spring.security.oauth2.resourceserver\=localhost` is not found from the reference documentation for Spring Boot 2.7.18:

https://docs.spring.io/spring-boot/docs/2.7.18/reference/html/application-properties.html#appendix.application-properties.security


<!-- Sent from Reviewable.io -->

2024-01-22 10:09 UTC, culka commented
This PR and branch will not be used in favour of one using a more recent base version of Tiamat.

2024-01-22 10:09 UTC, closed without merging